/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AVIPRegistry {
  export type BatchStruct = {
    batchId: BytesLike;
    merkleRoot: BytesLike;
    mmrRoot: BytesLike;
    submitter: AddressLike;
    timestamp: BigNumberish;
    itemCount: BigNumberish;
    previousBatchId: BytesLike;
    verified: boolean;
  };

  export type BatchStructOutput = [
    batchId: string,
    merkleRoot: string,
    mmrRoot: string,
    submitter: string,
    timestamp: bigint,
    itemCount: bigint,
    previousBatchId: string,
    verified: boolean
  ] & {
    batchId: string;
    merkleRoot: string;
    mmrRoot: string;
    submitter: string;
    timestamp: bigint;
    itemCount: bigint;
    previousBatchId: string;
    verified: boolean;
  };
}

export interface AVIPRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "MIN_BATCH_SIZE"
      | "authorizeValidator"
      | "getBatch"
      | "getBatchIdByIndex"
      | "getLatestBatch"
      | "isValidatorAuthorized"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeValidator"
      | "submitBatch"
      | "totalBatches"
      | "transferOwnership"
      | "unpause"
      | "verifyBatch"
      | "verifyChainIntegrity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchSubmitted"
      | "BatchVerified"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "ValidatorAuthorized"
      | "ValidatorRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getBatch", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBatchIdByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestBatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidatorAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBatch",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyChainIntegrity",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBatchIdByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidatorAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyChainIntegrity",
    data: BytesLike
  ): Result;
}

export namespace BatchSubmittedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    merkleRoot: BytesLike,
    mmrRoot: BytesLike,
    submitter: AddressLike,
    timestamp: BigNumberish,
    itemCount: BigNumberish,
    previousBatchId: BytesLike
  ];
  export type OutputTuple = [
    batchId: string,
    merkleRoot: string,
    mmrRoot: string,
    submitter: string,
    timestamp: bigint,
    itemCount: bigint,
    previousBatchId: string
  ];
  export interface OutputObject {
    batchId: string;
    merkleRoot: string;
    mmrRoot: string;
    submitter: string;
    timestamp: bigint;
    itemCount: bigint;
    previousBatchId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchVerifiedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    verifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAuthorizedEvent {
  export type InputTuple = [
    validator: AddressLike,
    authorizer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    authorizer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    validator: string;
    authorizer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRevokedEvent {
  export type InputTuple = [
    validator: AddressLike,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    validator: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AVIPRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AVIPRegistry;
  waitForDeployment(): Promise<this>;

  interface: AVIPRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  MIN_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  authorizeValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  getBatch: TypedContractMethod<
    [batchId: BytesLike],
    [AVIPRegistry.BatchStructOutput],
    "view"
  >;

  getBatchIdByIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getLatestBatch: TypedContractMethod<[], [string], "view">;

  isValidatorAuthorized: TypedContractMethod<
    [validator: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBatch: TypedContractMethod<
    [
      merkleRoot: BytesLike,
      mmrRoot: BytesLike,
      itemCount: BigNumberish,
      previousBatchId: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  totalBatches: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyBatch: TypedContractMethod<[batchId: BytesLike], [void], "nonpayable">;

  verifyChainIntegrity: TypedContractMethod<
    [batchId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BytesLike],
    [AVIPRegistry.BatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchIdByIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestBatch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isValidatorAuthorized"
  ): TypedContractMethod<[validator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBatch"
  ): TypedContractMethod<
    [
      merkleRoot: BytesLike,
      mmrRoot: BytesLike,
      itemCount: BigNumberish,
      previousBatchId: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyBatch"
  ): TypedContractMethod<[batchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyChainIntegrity"
  ): TypedContractMethod<[batchId: BytesLike], [boolean], "view">;

  getEvent(
    key: "BatchSubmitted"
  ): TypedContractEvent<
    BatchSubmittedEvent.InputTuple,
    BatchSubmittedEvent.OutputTuple,
    BatchSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "BatchVerified"
  ): TypedContractEvent<
    BatchVerifiedEvent.InputTuple,
    BatchVerifiedEvent.OutputTuple,
    BatchVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAuthorized"
  ): TypedContractEvent<
    ValidatorAuthorizedEvent.InputTuple,
    ValidatorAuthorizedEvent.OutputTuple,
    ValidatorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRevoked"
  ): TypedContractEvent<
    ValidatorRevokedEvent.InputTuple,
    ValidatorRevokedEvent.OutputTuple,
    ValidatorRevokedEvent.OutputObject
  >;

  filters: {
    "BatchSubmitted(bytes32,bytes32,bytes32,address,uint256,uint256,bytes32)": TypedContractEvent<
      BatchSubmittedEvent.InputTuple,
      BatchSubmittedEvent.OutputTuple,
      BatchSubmittedEvent.OutputObject
    >;
    BatchSubmitted: TypedContractEvent<
      BatchSubmittedEvent.InputTuple,
      BatchSubmittedEvent.OutputTuple,
      BatchSubmittedEvent.OutputObject
    >;

    "BatchVerified(bytes32,address,uint256)": TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;
    BatchVerified: TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "ValidatorAuthorized(address,address,uint256)": TypedContractEvent<
      ValidatorAuthorizedEvent.InputTuple,
      ValidatorAuthorizedEvent.OutputTuple,
      ValidatorAuthorizedEvent.OutputObject
    >;
    ValidatorAuthorized: TypedContractEvent<
      ValidatorAuthorizedEvent.InputTuple,
      ValidatorAuthorizedEvent.OutputTuple,
      ValidatorAuthorizedEvent.OutputObject
    >;

    "ValidatorRevoked(address,address,uint256)": TypedContractEvent<
      ValidatorRevokedEvent.InputTuple,
      ValidatorRevokedEvent.OutputTuple,
      ValidatorRevokedEvent.OutputObject
    >;
    ValidatorRevoked: TypedContractEvent<
      ValidatorRevokedEvent.InputTuple,
      ValidatorRevokedEvent.OutputTuple,
      ValidatorRevokedEvent.OutputObject
    >;
  };
}
